### ISSUE TITLE
Add diversity page

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2017-web#9]
The diversity page should show the following text:

https://raw.githubusercontent.com/yamila-moreno/pepa/master/es/pepa.txt

At the bottom of the text should show the link of the original text.

**Comment by xmnlab** [comment]
@olemis where can I save the file about diversity?

**Comment by olemis** [comment]
[Here](https://github.com/scipy-latinamerica/scipyla2017-web/blob/master/diversity/diversity.es.md)
